"use client";

import React, { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  inviteInfo,
  acceptInvite,
  rejectInvite,
} from "@myorg/api-client";

interface InviteInfo {
  inviterName: string;
  contactName: string;
  selfInvite?: boolean;
}

export default function AcceptInvitePage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get("token") ?? "";
  const [info, setInfo] = useState<InviteInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    // whenever the token changes clear previous state so we don't show an
    // out-of-date error while fetching again.
    setError(null);
    setInfo(null);

    if (!token) return setError("No invite token provided.");

    inviteInfo(token)
      .then(setInfo)
      .catch((err: any) => {
        let msg = err?.message || "Invalid or expired invitation.";
        if (err?.body?.error) {
          msg += ` (${err.body.error})`;
        }
        setError(msg);
      });
  }, [token]);

  const handleAccept = async () => {
    setProcessing(true);
    try {
      await acceptInvite(token);
      // redirect to the framework app (main application) with success flag and contacts tab
      const origin = typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3002';
      const frameworkUrl = origin.replace(':3002', ':3001');
      router.replace(`${frameworkUrl}/?accepted=true&tab=people`);
    } catch (err: any) {
      // redirect to the framework app with failure flag and contacts tab
      const origin = typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3002';
      const frameworkUrl = origin.replace(':3002', ':3001');
      router.replace(`${frameworkUrl}/?failed=true&tab=people`);
    } finally {
      setProcessing(false);
    }
  };

  const handleReject = async () => {
    setProcessing(true);
    try {
      await rejectInvite(token);
      // redirect the user to the framework app (port 3001) with a flag and contacts tab
      const origin = window.location.origin.replace(':3002', ':3001');
      router.replace(`${origin}/?rejected=true&tab=people`);
    } catch {
      setError("Failed to reject invitation.");
    } finally {
      setProcessing(false);
    }
  };

  if (error) {
    return (
      <main className="invite-page">
        <div className="invite-card">
          <div className="invite-header">
            <span className="material-icons invite-icon invite-icon--error">error_outline</span>
            <h1 className="invite-title">Invitation Error</h1>
          </div>
          <p className="invite-message invite-message--error">{error}</p>
          <button
            onClick={() => {
              const origin = window.location.origin.replace(':3002', ':3001');
              window.location.replace(`${origin}/?tab=people`);
            }}
            className="invite-button invite-button--secondary"
          >
            Return to Contacts
          </button>
        </div>
      </main>
    );
  }

  if (!info) {
    return (
      <main className="invite-page">
        <div className="invite-card">
          <div className="invite-loading">
            <div className="invite-spinner"></div>
            <p>Loading invitation…</p>
          </div>
        </div>
      </main>
    );
  }

  if (info.selfInvite) {
    return (
      <main className="invite-page">
        <div className="invite-card">
          <div className="invite-header">
            <span className="material-icons invite-icon invite-icon--warning">info</span>
            <h1 className="invite-title">Self-Invitation</h1>
          </div>
          <p className="invite-message">
            This invitation link was generated by you (<strong>{info.inviterName}</strong>),
            so it cannot be used. It's intended for someone else (
            <strong>{info.contactName}</strong>).
          </p>
          <button
            onClick={() => router.push('/')}
            className="invite-button invite-button--primary"
          >
            Return to Contacts
          </button>
        </div>
      </main>
    );
  }

  return (
    <main className="invite-page">
      <div className="invite-card">
        <div className="invite-header">
          <span className="material-icons invite-icon invite-icon--invite">person_add</span>
          <h1 className="invite-title">Contact Invitation</h1>
        </div>
        <div className="invite-content">
          <p className="invite-message">
            <strong>{info.inviterName}</strong> wants to add you to their contacts as{' '}
            <strong>{info.contactName}</strong>.
          </p>
          <div className="invite-actions">
            <button
              onClick={handleAccept}
              disabled={processing}
              className="invite-button invite-button--primary"
            >
              {processing ? (
                <>
                  <div className="invite-spinner invite-spinner--small"></div>
                  Accepting…
                </>
              ) : (
                <>
                  <span className="material-icons">check</span>
                  Accept Invitation
                </>
              )}
            </button>
            <button
              onClick={handleReject}
              disabled={processing}
              className="invite-button invite-button--secondary"
            >
              {processing ? (
                <>
                  <div className="invite-spinner invite-spinner--small"></div>
                  Rejecting…
                </>
              ) : (
                <>
                  <span className="material-icons">close</span>
                  Decline
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </main>
  );
}
