"use client";

import React, { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  inviteInfo,
  acceptInvite,
  rejectInvite,
} from "@myorg/api-client";

interface InviteInfo {
  inviterName: string;
  contactName: string;
  selfInvite?: boolean;
}

export default function AcceptInvitePage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get("token") ?? "";
  const [info, setInfo] = useState<InviteInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    // whenever the token changes clear previous state so we don't show an
    // out-of-date error while fetching again.
    setError(null);
    setInfo(null);

    if (!token) return setError("No invite token provided.");

    inviteInfo(token)
      .then(setInfo)
      .catch((err: any) => {
        let msg = err?.message || "Invalid or expired invitation.";
        if (err?.body?.error) {
          msg += ` (${err.body.error})`;
        }
        setError(msg);
      });
  }, [token]);

  const handleAccept = async () => {
    setProcessing(true);
    try {
      await acceptInvite(token);
      // send the user back to the app's root; query flags allow UI to show
      // a toast or similar if desired
      router.replace("/?accepted=true");
    } catch (err: any) {
      let msg = "Failed to accept invitation.";
      if (err?.body?.message) msg = err.body.message;
      setError(msg);
    } finally {
      setProcessing(false);
    }
  };

  const handleReject = async () => {
    setProcessing(true);
    try {
      await rejectInvite(token);
      // redirect the user to the framework app (port 3001) with a flag
      const origin = window.location.origin.replace(':3002', ':3001');
      router.replace(`${origin}/?rejected=true`);
    } catch {
      setError("Failed to reject invitation.");
    } finally {
      setProcessing(false);
    }
  };

  if (error) {
    return (
      <main style={{ padding: 32 }}>
        <h1>Invitation</h1>
        <p style={{ color: "red" }}>{error}</p>
      </main>
    );
  }

  if (!info) {
    return (
      <main style={{ padding: 32 }}>
        <p>Loading invitation…</p>
      </main>
    );
  }

  if (info.selfInvite) {
    return (
      <main style={{ padding: 32 }}>
        <h1>Invitation</h1>
        <p>
          This invitation link was generated by you (<strong>{info.inviterName}</strong>),
          so it cannot be used.  It’s intended for someone else (
          <strong>{info.contactName}</strong>).
        </p>
      </main>
    );
  }

  return (
    <main style={{ padding: 32 }}>
      <h1>Invitation</h1>
      <p>
        <strong>{info.inviterName}</strong> has asked to add you to their
        contacts as <strong>{info.contactName}</strong>.
      </p>
      <div style={{ display: "flex", gap: 8, marginTop: 16 }}>
        <button onClick={handleAccept} disabled={processing}>
          {processing ? "Accepting…" : "Accept"}
        </button>
        <button onClick={handleReject} disabled={processing}>
          {processing ? "Rejecting…" : "Reject"}
        </button>
      </div>
    </main>
  );
}
